### ISSUE TITLE
Decrease sampling rate and drop unsampled transactions

### ISSUE THREAD

**Issue by sqren** [elastic/apm-integration-testing#1241]
Sometime in the future APM Server will drop unsampled transactions by default. This will impact the APM ui, and to prepare ourselves for this shift I suggest that apm-integration-testing by default will drop unsampled transactions also. For this to have any noticable effect we should also reduce the sampling rate from 100% to something else. Perhaps 10% or maybe even 1%?

To drop unsampled transactions set `keep_unsampled: false` in APM Server:
https://www.elastic.co/guide/en/apm/server/master/transaction-metrics.html#sampling-keep_unsampled

The easiest way to change the sampling rate for all agents might be via [central configuration API](https://www.elastic.co/guide/en/kibana/current/agent-config-api.html). This would also ensure that we actually use central config on a daily basis.

**Comment by cachedout** [comment]
Hi @sqren 

Thanks for the heads-up here. I'm also going to cc: @graphaelli because I think he might have some input.

We can certainly add this setting to the APM integration test suite by default if that's what the teams want to do. (That's quite easy.)

If we also want to change the same rate for each agent, we just need guidance on specifically what you want that value to be.

I think the next step here is to see what @graphaelli says and maybe we'll need to bring some agent teams in as well to figure out how far we want to decrease the sample rates on the agent side. Once all those decisions are made, a PR should be no problem.

Lastly, is this also something you want to happen on the observability test clusters? If so, we'll need to open a separate issue to track that but we can wait until after we've made decisions on the above.

**Comment by sqren** [comment]
> If we also want to change the same rate for each agent, we just need guidance on specifically what you want that value to be.

Let's say 10% but I'm okay with anything below 10% really.

**Comment by sqren** [comment]
> Lastly, is this also something you want to happen on the observability test clusters? If so, we'll need to open a separate issue to track that but we can wait until after we've made decisions on the above.

Yes, I think it would be great to have on the obs clusters as well. But fine to focus on apm-integration-testing first, and then tackle the obs clusters later.

**Comment by graphaelli** [comment]
I think this makes a lot of sense to make it simple to drop unsampled tranasaction in apm-it, making it the default for 7.16+ clusters in apm-it with an option to keep unsampled sounds like a good path forward.  

As @sqren wrote in the original, we'll need a corresponding drop in sample rates for this to be useful for testing metrics.  While central configuration would be nice, I propose we start with a straightforward option like `--opbeans-$lang-sample-rate`.  This could even default to a per-service defined default (`DEFAULT_SAMPLE_RATE` class attribute).

@felixbarny any concerns with @sqren's proposal?

**Comment by felixbarny** [comment]
No concerns, SGTM

**Comment by cachedout** [comment]
A PR is now up for review: https://github.com/elastic/apm-integration-testing/pull/1255

**Comment by sqren** [comment]
@cachedout Has this been released on the edge cluster? I'm not seeing any unsampled transactions and wondering why that is.

**Comment by cachedout** [comment]
@sqren The changes made in https://github.com/elastic/apm-integration-testing/pull/1255 only affect the APM Integration tests. 

You wrote above:

`Yes, I think it would be great to have on the obs clusters as well. But fine to focus on apm-integration-testing first, and then tackle the obs clusters later.`

We've done the first part but not the second. :)

I have opened https://github.com/elastic/observability-test-environments/issues/1911 to track the request to add these same settings to the edge cluster.

**Comment by sqren** [comment]
Ahh, makes sense. Thanks @cachedout !
