### ISSUE TITLE
Remove agent tests

### ISSUE THREAD

**Issue by axw** [elastic/apm-integration-testing#1523]
The agent integration tests are of limited value. The tests are fairly basic, and we have since added fake APM Server implementations to the agent repos, which validate payloads.

The cost of maintaining the integration tests exceeds the value they are providing, therefore we should remove them. Later on we might replace them with something a little more maintainable. For example: disentangling stack/server provisioning, and distributing the tests to each agent repository. We can come back to that as needed.

**Comment by cachedout** [comment]
@axw Would you like us to also remove the test pipelines from Jenkins [which can be found here](https://apm-ci.elastic.co/job/apm-integration-tests/)?

**Comment by axw** [comment]
@cachedout yes, please - thank you.

**Comment by cachedout** [comment]
After looking at this, it makes more sense to leave the pipelines in place until such time that we choose to remove the repo entirely. I was going to kill the cron trigger so that we only ran this pipeline on pushes to the branch, but @kuisathaverat [beat me to it](https://github.com/elastic/apm-integration-testing/pull/1528)! I don't think we need any additional change here.
