### ISSUE TITLE
--no-XXXXbeat options does not disable beats when you use it with --all

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#483]
If you run the following command the docker-compose file will have beats for running and it should not

`scripts/compose.py start master --no-kibana --no-heartbeat --no-metricbeat --no-filebeat --all`

related to https://github.com/elastic/apm-integration-testing/pull/476

**Comment by bartier** [comment]
@kuisathaverat Hi! I'm new here, but I would like to try to fix this :smiley:

In my tests, I understand that when `setup()` from `scripts/compose.py` is called the `start_handler` method in  `scripts/modules/cli.py` is called.

For each service, based on the args options and service attributes (if it is opbeans for example), the for loop decides if the services is going to be started. 
 
```
...
...
        for service in self.services:
            service_enabled = args.get("enable_" + service.option_name())
            is_opbeans_service = issubclass(service, OpbeansService) or service is OpbeansRum
            is_opbeans_sidecar = service.name() in opbeans_sidecars
            is_opbeans_2nd = service.name() in opbeans_2nds
            is_obs = issubclass(service, BeatMixin)
            if (service_enabled or
                    (all_opbeans and is_opbeans_service and not is_opbeans_2nd) or
                    (any_opbeans and is_opbeans_sidecar and not is_opbeans_2nd) or
                    (run_all and is_obs and not is_opbeans_2nd)):
                selections.add(service(**args))
...
...
```

If you run with `scripts/compose.py start master --no-kibana --no-heartbeat --no-metricbeat --no-filebeat --all` like you said:

The `heartbeat`, `metricbeat` services is running because of the following logic:

Variables states for Filebeat, Heartbeat, Metricbeat, Packetbeat:
 ```
service_enabled = False
is_opbeans_service = False
is_opbeans_sidecar = False
is_opbeans_2nd = False
is_obs = True
```

The `if` statement is being true because `run_all and is_obs and not is_opbeans_2nd` is resolved to `True`, see:

`run_all and is_obs and not is_opbeans_2nd`
`True and True and not False`

Even that I Know why this is breaking (because of the third condition), I'm not sure how the fix should be created.

I have one question and "shot" how to solve but I'm not sure if this is a possible solution. See below:

----

Using `--all` flag **all** Beats should run? 

Examples:
`--all`: All 4 beats should run
`--all --no-filebeat`: Only Heartbeat, Metricbeat and PacketBeat.

The 4 Beats is currently set to `false` in `scripts/modules/beats.py` file because there is no `@staticmethod` in their definition like this:
```
    @staticmethod
    def enabled():
        return True
```

If **all** Beats had the enabled set to `true` like above the `if statement` could be converted to only the two first conditions:
```
            if (service_enabled or
                    (all_opbeans and is_opbeans_service and not is_opbeans_2nd) or
                    (any_opbeans and is_opbeans_sidecar and not is_opbeans_2nd)):
                selections.add(service(**args))
```


Can you please provide more information about it?

Thanks in advance and sorry for any missinformation, I'm actually newbie in Elastic Stack.

**Comment by kuisathaverat** [comment]
the --no-XXXX parameters should disable any service https://github.com/elastic/apm-integration-testing/blob/bb9cae6460a5efdd7dba08e90d5d15df8f870753/scripts/modules/cli.py#L200-L206, so it is a matter of precedence on the evaluation, not sure how to fix it. 
The other day I was thinking to close the issue, it does not have too much sense, I mean,  if you set `--all` you want to execute everything, for a few things the --no-XXX settings can make sense but not for everything if you what a subset of thing to launch you have other flags to enable only what you need. We are trying to reduce the complexity of the compose.py by reducing the number of flags to those taht make sense, and are really used.

**Comment by bartier** [comment]
@kuisathaverat Thanks for your reply :)

I'm not sure if I made myself clear (English is not my first language, sorry), but I'd like to discuss I guess to solve this in a simple matter:

Does adding `def enabled(): return True ` in Beats classes  and removing the third condition of the `if` a valid solution? ElasticSearch class for example has this method:
https://github.com/elastic/apm-integration-testing/blob/40e4d9ba407bf75d5a5a58132c6b89154a7a96c8/scripts/modules/elastic_stack.py#L670-L672

Beats would have this definition of `def enabled()` like ElasticSearch:
https://github.com/elastic/apm-integration-testing/blob/40e4d9ba407bf75d5a5a58132c6b89154a7a96c8/scripts/modules/beats.py#L143-L165



The line 527 would be removed:
https://github.com/elastic/apm-integration-testing/blob/40e4d9ba407bf75d5a5a58132c6b89154a7a96c8/scripts/modules/cli.py#L518-L528

I made a test with this scenario and the `-no-XXXXbeat` worked because the enable_XXXbeat is `True` by default and with `-no-XXXXbeat` the `service_enabled` in the `if statement` at line 518 would not be True to add the beat to the `selections`

It is just I guess anyway. I'll wait your considerations to close or not this issue. Thanks.

**Comment by kuisathaverat** [comment]
>Does adding def enabled(): return True in Beats classes and removing the third condition of the if a valid solution? ElasticSearch class for example has this method

I did not test it, but I'd said that would break something for sure, this change affects all stack services, it is a matter of making the change and run the test `make test-compose`

**Comment by kuisathaverat** [comment]
there is a workaround so we can close it
