### ISSUE TITLE
[Automation][integration-testing] launch Apache HTTP server, HAProxy, and NGINX containers

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#500]
in order to test Beats modules, we will need to launch the Apache HTTP server, HAProxy,  and NGINX containers, probably more to tests other modules.

**Comment by mdelapenya** [comment]
Hey @Andres-Rodriguez , is this something that could be closed as overlapping the end2end tests we are already doing for metricbeat?

**Comment by andresrc** [comment]
If this issue is about having the services available in the test clusters we should keep it, as we want an environment with several data sources.

If it is about improving how the automatic tests are run, yes there are other initiatives in place (both e2e and improvements to integrations tests) and we should close this. Those initiatives may need some involvement from the team but specific issues will be open when needed.

Thanks

**Comment by kuisathaverat** [comment]
>If this issue is about having the services available in the test clusters we should keep it, as we want an environment with several data sources.

we have those services deployed right now. This issue is about implementing the same with docker-compose, I think we can close it, it is mostly the same than the e2e initiative
