### ISSUE TITLE
Log correlation on integration test

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#643]
We are modifying the Opbeans projects to generate a verbose JSON output with APM traces, this would help to make the Logs correlation, the integration test is the point where all those efforts will come together.
We've started to see some issues to make all the Opbeans work together https://github.com/elastic/apm-integration-testing/issues/636

* Not all Opbeans use the same field for the log message (msg, message, event, ...), difficult to resolve means to rename every field and has problems when you have to overwrite the messages field from the Filebeat document, so it means a complex Filebeat config we do not want.
* Not all Opbeans have a pure JSON log output, it could be resolved by applying filters in Filebeat
* Not all Opbeans uses the same type for the same field (service: Object, service, String), the only solution could be to rename those fields, this would make the Filebeat configuration complex.

a common schema for those common fields could help to resolve some of the issues.

cc @elastic/apm

**Comment by alvarolobato** [comment]
@Lior-Reuven @axw please have a look at this, is this an agent implementation problem or an opbeans implementation detail?

**Comment by axw** [comment]
This is an issue with Opbeans and apm-integration-testing. I agree we should strongly consider dogfooding ecs-logging across Opbeans.

**Comment by felixbarny** [comment]
Opbeans Java is using the ecs-logging-java module already. However, the agent itself still logs as plain-text, so the Filebeat configuration should check if a line is a JSON and only try to parse it then. See also https://github.com/elastic/apm-integration-testing/issues/639

Going forward it probably makes sense that the agent itself also logs ECS-compatible JSON.

**Comment by kuisathaverat** [comment]
>Opbeans Java is using the ecs-logging-java module already. However, the agent itself still logs as plain-text

I'd say that it is a minor issue is easier to filter NO-JSON log lines from the logs than try to fit several JSON formats

**Comment by felixbarny** [comment]
Some thoughts:

- I'm not sure how useful centralized logging is without parsing anything in the logline. At least the timestamp is something which should be parsed out of the plain-text. Otherwise, the `@timestamp` will be set to the time Filebeat reads the line which might be off completely. But also things like the log.level is some really basic information which is almost mandatory to have parsed out.
- Users struggle with grok. Especially because there are so many different logging formats. That almost makes it impossible to have some kind of cookbook/copy-pasteable examples. The ECS loggers greatly help with that.
- The ECS loggers still require users to do some log configuration changes in order to get started.
- I think the ultimate goal should be that we only provide a single agent. That agent would then auto-discover all applications and inject our APM agents into them. We could then automatically add a logging appender that sends ECS-formatted logs to an endpoint of the single agent or to a file that is known to the agent.

> Even if we do that I think we should have a simpler, faster way to be able to link trace to logs.

We already have that capability: when jumping from the APM App to the Logs App, it searches for `trace.id: 72ace1d or 72ace1d` which does a full-text search for the trace id so that it does not require the trace id to be actually parsed out into a separate field. However, linking from the Logs App to the APM App does only work if there is a dedicated `trace.id` field.

> What are your thoughts on appending the traceId at the beggining(or end, begining is probably easier for parsing it with filebeat) of the log line and parsing it with FileBeat?

We could have a processor in Filebeat which automatically detects key/value pairs in the format of `<key>=<value>` and create separate fields for it. One potential pitfall is that it can lead to mapping explosions if we want to index all unknown (non-ECS) fields.

**Comment by kuisathaverat** [comment]
Thinking about this, probably the most simple solution is to integrate Filebeat on the Opbeans Docker containers, in that way every Opbeans has his own Filebeat configuration isolated from the rest. This approach is also valid for test environments.

**Comment by beniwohli** [comment]
> We could have a processor in Filebeat which automatically detects key/value pairs in the format of `<key>=<value>` and create separate fields for it. One potential pitfall is that it can lead to mapping explosions if we want to index all unknown (non-ECS) fields.

FWIW, I used a logging service in the past that would detect and transform any JSON dictionary, as long as it was at the end of the log line. This made the getting started experience for structured logging super smooth. Just append any key/values you might want to extract as JSON, done. I always wondered why Filebeat doesn't have a similar processor. Maybe it's considered too computationally heavy to autodetect trailing JSON...

**Comment by kuisathaverat** [comment]
it is enabled on the integration tests for the Agents Go, Java, Python, and Ruby, we also enabled it on the test environments for the agents Go and Ruby. We are working now to enable Python and Java.

**Comment by kuisathaverat** [comment]
test environments are also configured for log correlation.

**Comment by kuisathaverat** [comment]
PRs related 
* https://github.com/elastic/apm-integration-testing/issues/643 
* https://github.com/elastic/apm-integration-testing/pull/637 
* https://github.com/elastic/observability-test-environments/pull/172 
* https://github.com/elastic/observability-test-environments/pull/171 
* https://github.com/elastic/observability-test-environments/pull/170 
* https://github.com/elastic/observability-test-environments/pull/165 
* https://github.com/elastic/opbeans-ruby/pull/25 
* https://github.com/elastic/opbeans-ruby/pull/23 
* https://github.com/elastic/observability-test-environments/pull/181
* https://github.com/elastic/observability-test-environments/pull/180  
* https://github.com/elastic/observability-test-environments/pull/179 
* https://github.com/elastic/observability-test-environments/pull/178 
* https://github.com/elastic/observability-test-environments/pull/177 
* https://github.com/elastic/observability-test-environments/pull/176
